### ISSUE TITLE
[Question] Lots of  questions.

### ISSUE THREAD

**Issue by yodaluca23** [Dynvsty/McFlurry#1]
First off, please open up the discussions features.
Secondly, does this  change the client at all? Could it be detectable, say on Hypixel, like different from  just clicking it manually?
Does this work in fullscreen, sense you can't do it manually even in fullscreen...
Thank you!

**Comment by Dynvsty** [comment]
> First off, please open up the discussions features.
> 
> Secondly, does this  change the client at all? Could it be detectable, say on Hypixel, like different from  just clicking it manually?
> 
> Does this work in fullscreen, sense you can't do it manually even in fullscreen...
> 
> Thank you!

No, this doesn't change anything on the client side, so it's undetectable. It currently doesn't work in full screen, but I'm trying to find a way to get it to.
Discussions have been opened, thanks for the suggestion
